### ISSUE TITLE
小TiD笔记

### ISSUE THREAD

**Issue by Tidra** [BillScott1024/blog-friends#8]
|  选项   | 描述  |
|  ----  | ----  |
| title  | 小TiD笔记|
| url  | [主页链接](https://www.tidnotes.top/) |
| avatar  | https://cdn.cbd.int/tidnotes-blog-static@1.0.0/img/avatar.jpg |
| description  | 技术无止境，随心随所记 |
| screenshot  | https://npm.elemecdn.com/anzhiyu-blog@1.1.6/img/post/common/anzhiy.cnp.jpg |

# 在下面填写↓

```json
{
  "title": "小TiD笔记",
  "url": "https://www.tidnotes.top/",
  "avatar": "https://cdn.cbd.int/tidnotes-blog-static@1.0.0/img/avatar.jpg",
  "screenshot": "https://npm.elemecdn.com/anzhiyu-blog@1.1.6/img/post/common/anzhiy.cnp.jpg",
  "description": "技术无止境，随心随所记"
}
```

**Comment by BillScott1024** [comment]
Added
